const map=L.map('map',{preferCanvas:true,zoomControl:true}).setView([-22.45,-48.4],7);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);

const DATA_FILES=['data/backbone-1.geojson','data/backbone-2.geojson','data/backbone-3.geojson','data/backbone-4.geojson'];
const FIRE_DATA='data/fire-core.json';
const ENERGY_DATA='data/energy-core.json';
const FIRE_REFRESH_MS=120000;
const ENERGY_REFRESH_MS=300000;
const WEATHER_DATA='data/weather-risk.json';
const FORECAST_SPI_DATA='data/previsao-spi.json';
const FORECAST_SPI_REFRESH_MS=30*60*1000;
let forecastSpi={regioes:[]};
const WEATHER_REFRESH_MS=300000;
const DEFESA_DATA='data/defesa-civil.json';
const DEFESA_REFRESH_MS=300000;
const SITES_DATA='data/sites.json';
const SITES_REFRESH_MS=1800000;
let allFeatures=[],layer=null,fireEvents=[],weatherEvents=[],energyEvents=[],defesaEvents=[],siteEvents=[];
let weatherMeta={};
const fireLayer=L.layerGroup().addTo(map);
const weatherLayer=L.layerGroup().addTo(map);
const relatedBackboneLayer=L.layerGroup().addTo(map);
const energyLayer=L.layerGroup().addTo(map);
const defesaLayer=L.layerGroup().addTo(map);
const sitesLayer=L.layerGroup().addTo(map);

const colorFor=c=>({ALTA:'#7c3aed',MEDIA:'#f59e0b',BAIXA:'#ef4444',SEM_REFERENCIA:'#64748b'})[c]||'#38bdf8';
const fireColor=c=>({URGENTE:'#dc2626',ATENCAO:'#f59e0b',MONITORAMENTO:'#16a34a'})[(c||'').toUpperCase()]||'#64748b';
const energyColor=n=>({CRITICO:'#dc2626',ALTO:'#ea580c',ATENCAO:'#f59e0b',BAIXO:'#0ea5e9',MONITORAMENTO:'#64748b'})[(n||'').toUpperCase()]||'#64748b';
const weatherColor=c=>({CRITICO:'#dc2626',ALTO:'#ea580c',ATENCAO:'#f59e0b',MONITORAMENTO:'#0ea5e9'})[(c||'').toUpperCase()]||'#64748b';
const norm=v=>(v??'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const esc=v=>(v??'—').toString().replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtKm=v=>Number.isFinite(Number(v))?`${Number(v).toFixed(3)} km`:'—';
const windCompass=d=>{const n=Number(d);if(!Number.isFinite(n))return '—';const pts=['N','NE','L','SE','S','SO','O','NO'];return `${pts[Math.round((((n%360)+360)%360)/45)%8]} (${Math.round(n)}°)`;};
const weatherCodeLabel=c=>({0:'Céu limpo',1:'Predom. limpo',2:'Parcialmente nublado',3:'Nublado',45:'Nevoeiro',48:'Nevoeiro com geada',51:'Garoa leve',53:'Garoa',55:'Garoa forte',61:'Chuva leve',63:'Chuva',65:'Chuva forte',71:'Neve leve',73:'Neve',75:'Neve forte',80:'Pancadas leves',81:'Pancadas',82:'Pancadas fortes',95:'Tempestade',96:'Tempestade c/ granizo',99:'Tempestade forte c/ granizo'})[Number(c)]||'Condição meteorológica';
function forecastHtml(e){const ph=Array.isArray(e.previsao_horaria)?e.previsao_horaria:[];if(!ph.length)return '<div class="forecast-empty">Previsão horária ainda não disponível para este município.</div>';return `<div class="forecast-grid">${ph.slice(0,8).map(x=>{const dt=x.data_hora?new Date(x.data_hora):null;const hh=dt&&!Number.isNaN(dt.getTime())?dt.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):(x.data_hora||'—');return `<div class="forecast-card ${x.tempestade?'forecast-storm':''}"><b>${esc(hh)}</b><span>${esc(weatherCodeLabel(x.weather_code))}</span><span>💨 ${esc(x.vento_kmh)} km/h • ${esc(windCompass(x.direcao_vento_graus))}</span><span>🌬️ raj. ${esc(x.rajada_kmh)} km/h</span><span>🌧️ ${esc(x.precipitacao_mm)} mm • ${esc(x.probabilidade_chuva)}%</span>${x.tempestade?'<strong>⚡ Tempestade prevista</strong>':''}</div>`}).join('')}</div>`;}

function popupHtml(p){return `<b>${esc(p.trecho||'Backbone')}</b><br>${esc(p.ponta_a)} — ${esc(p.municipio_a)}<br>${esc(p.ponta_b)} — ${esc(p.municipio_b)}<br>Cabo: <b>${esc(p.cabo)}</b><br>Confiança: ${esc(p.confianca)}`;}
function detailsHtml(p){const rows=[['Trecho',p.trecho],['Cabo',p.cabo],['Capacidade',p.capacidade],['Cluster',p.cluster],['Ponta A',`${p.ponta_a||'—'} — ${p.municipio_a||'—'}`],['Ponta B',`${p.ponta_b||'—'} — ${p.municipio_b||'—'}`],['Extensão',p.extensao_km?`${Number(p.extensao_km).toFixed(2)} km`:'—'],['Confiança',p.confianca],['Fonte',p.fonte]];return `<div class="panel-title">Trecho selecionado</div><h3>${esc(p.trecho||'Backbone')}</h3>${rows.map(r=>`<div class="row"><span>${esc(r[0])}</span><span>${esc(r[1]??'—')}</span></div>`).join('')}`;}

function render(){const cl=document.getElementById('clusterFilter').value,cf=document.getElementById('confidenceFilter').value,q=norm(document.getElementById('searchBox').value);const feats=allFeatures.filter(f=>{const p=f.properties||{};if(cl&&p.cluster!==cl)return false;if(cf&&p.confianca!==cf)return false;if(q&&!norm([p.trecho,p.cabo,p.cluster,p.ponta_a,p.ponta_b,p.municipio_a,p.municipio_b].join(' ')).includes(q))return false;return true;});if(layer)layer.remove();layer=L.geoJSON({type:'FeatureCollection',features:feats},{style:f=>({color:colorFor(f.properties.confianca),weight:3,opacity:.78}),onEachFeature:(f,l)=>{l.bindPopup(popupHtml(f.properties));l.on('click',()=>document.getElementById('details').innerHTML=detailsHtml(f.properties));l.on('mouseover',()=>l.setStyle({weight:6,opacity:1}));l.on('mouseout',()=>layer.resetStyle(l));}}).addTo(map);document.getElementById('rotas').textContent=feats.length.toLocaleString('pt-BR');if(feats.length&&q)try{map.fitBounds(layer.getBounds(),{padding:[20,20],maxZoom:12})}catch(e){}}
function populate(){const ps=allFeatures.map(f=>f.properties||{});const uniq=k=>[...new Set(ps.map(p=>p[k]).filter(Boolean))];document.getElementById('clusters').textContent=uniq('cluster').length;document.getElementById('cabos').textContent=uniq('cabo').length;document.getElementById('municipios').textContent=new Set(ps.flatMap(p=>[p.municipio_a,p.municipio_b]).filter(Boolean)).size;const s=document.getElementById('clusterFilter');uniq('cluster').sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o)});render();}

function firePopupHtml(e){return `<div class="fire-popup"><b style="color:${fireColor(e.classificacao)}">🔥 ${esc(e.classificacao)}</b><br><b>${esc(e.id_evento)}</b><br>Município: ${esc(e.municipio)}<br>Última detecção: ${esc(e.ultima_deteccao)}<br>Backbone: <b>${esc(e.backbone)}</b><br>Cabo: ${esc(e.cabo)}<br>Distância: <b>${fmtKm(e.distancia_backbone_km)}</b><br>Confiança: ${esc(e.confianca_rota)}<br>Satélite: ${esc(e.satelite)}<br>Detecções: ${esc(e.deteccoes)}</div>`;}
function fireDetailsHtml(e){const rows=[['Classificação',e.classificacao],['Evento',e.id_evento],['Município',e.municipio],['Última detecção',e.ultima_deteccao],['Backbone',e.backbone],['Cabo',e.cabo],['Distância',fmtKm(e.distancia_backbone_km)],['Confiança',e.confianca_rota],['Satélite',e.satelite],['Detecções',e.deteccoes]];return `<div class="panel-title">🔥 Fire Core</div><h3 class="fire-title" style="color:${fireColor(e.classificacao)}">${esc(e.classificacao)}</h3>${rows.map(r=>`<div class="row"><span>${esc(r[0])}</span><span>${esc(r[1]??'—')}</span></div>`).join('')}`;}
function highlightBackbone(e){relatedBackboneLayer.clearLayers();const f=allFeatures.find(x=>{const p=x.properties||{};return (e.id_backbone&&p.id_backbone===e.id_backbone)||(e.backbone&&p.trecho===e.backbone);});if(!f)return;L.geoJSON(f,{style:{color:fireColor(e.classificacao),weight:8,opacity:1}}).addTo(relatedBackboneLayer).bringToFront();}
function renderFire(){fireLayer.clearLayers();relatedBackboneLayer.clearLayers();const enabled=document.getElementById('fireToggle')?.checked!==false;document.getElementById('fireCount').textContent=`${fireEvents.length} ativo${fireEvents.length===1?'':'s'}`;if(!enabled)return;fireEvents.forEach(e=>{const lat=Number(e.latitude),lon=Number(e.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;const color=fireColor(e.classificacao);const marker=L.circleMarker([lat,lon],{radius:10,color:'#fff',weight:2,fillColor:color,fillOpacity:.95});marker.bindPopup(firePopupHtml(e));marker.bindTooltip(`🔥 ${e.classificacao||'FIRE'} • ${e.id_evento||''}`);marker.on('click',()=>{document.getElementById('details').innerHTML=fireDetailsHtml(e);highlightBackbone(e);});marker.addTo(fireLayer);const p=e.ponto_mais_proximo||{};const plat=Number(p.latitude),plon=Number(p.longitude);if(Number.isFinite(plat)&&Number.isFinite(plon)){L.polyline([[lat,lon],[plat,plon]],{color,weight:3,opacity:.85,dashArray:'8 8'}).addTo(fireLayer);L.circleMarker([plat,plon],{radius:5,color,weight:2,fillColor:'#fff',fillOpacity:1}).addTo(fireLayer);}});}


function energyPopupHtml(e){const ds=(e.distribuidoras||[]).join(', ')||'—';const st=(e.status||[]).join(', ')||'—';return `<div class="energy-popup"><b style="color:${energyColor(e.nivel)}">⚡⧸ SEM ENERGIA</b><br><b>${esc(e.regiao)}</b><br>${esc(e.municipio)}<br>Distribuidora: ${esc(ds)}<br>Status: ${esc(st)}<br>Ocorrências: ${(e.ocorrencias||[]).length}</div>`;}
function energyDetailsHtml(e){const rows=[['Condição','SEM ENERGIA'],['Região',e.regiao],['Município',e.municipio],['Distribuidora(s)',(e.distribuidoras||[]).join(', ')||'—'],['Status',(e.status||[]).join(', ')||'—'],['Ocorrência(s)',(e.ocorrencias||[]).join(', ')||'—'],['Referência geográfica',e.origem_coordenada],['Confiança',e.confianca_geografica]];return `<div class="panel-title">⚡ Energia</div><h3 class="energy-title" style="color:${energyColor(e.nivel)}">⚡⧸ ${esc(e.regiao)}</h3>${rows.map(r=>`<div class="row"><span>${esc(r[0])}</span><span>${esc(r[1]??'—')}</span></div>`).join('')}`;}
function energyIcon(e){const z=map.getZoom();const compact=z<=7;const size=compact?8:11;return L.divIcon({className:'energy-outage-wrapper',html:`<div class="energy-outage-icon ${compact?'energy-compact':''}"><span class="energy-bolt"></span><span class="energy-slash"></span></div>`,iconSize:[size,size],iconAnchor:[size/2,size/2],popupAnchor:[0,-8]});}
function renderEnergy(){energyLayer.clearLayers();const enabled=document.getElementById('energyToggle')?.checked!==false;const count=document.getElementById('energyCount');if(count)count.textContent=`${energyEvents.length} região${energyEvents.length===1?'':'ões'}`;if(!enabled)return;energyEvents.forEach(e=>{const lat=Number(e.latitude),lon=Number(e.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;const marker=L.marker([lat,lon],{icon:energyIcon(e),zIndexOffset:700});marker.bindPopup(energyPopupHtml(e));marker.bindTooltip(`⚡⧸ ${e.regiao||''} • ${e.municipio||''}`);marker.on('click',()=>{document.getElementById('details').innerHTML=energyDetailsHtml(e);});marker.addTo(energyLayer);});}
async function loadEnergy(){try{const r=await fetch(`${ENERGY_DATA}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`Energy HTTP ${r.status}`);const obj=await r.json();energyEvents=Array.isArray(obj.regioes)?obj.regioes:[];renderEnergy();const c=document.getElementById('energyCount');if(c)c.title=obj.gerado_em?`Atualizado: ${obj.gerado_em}`:'Energy Core';}catch(err){console.error('Falha Energy Core',err);const c=document.getElementById('energyCount');if(c)c.textContent='erro';}}
async function loadFire(){try{const r=await fetch(`${FIRE_DATA}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`Fire HTTP ${r.status}`);const obj=await r.json();fireEvents=Array.isArray(obj.eventos_ativos)?obj.eventos_ativos:[];renderFire();document.getElementById('fireCount').title=obj.gerado_em?`Atualizado: ${obj.gerado_em}`:'Fire Core';}catch(err){console.error('Falha Fire Core',err);document.getElementById('fireCount').textContent='erro';}}

const climateSeverityRank=n=>({CRITICO:4,ALTO:3,ATENCAO:2,MONITORAMENTO:1})[norm(n)]||1;
function climateEventType(e){const rain=Number(e.chuva_total_mm||0),gust=Number(e.rajada_kmh||0);if(e.tempestade)return 'Tempestade';if(rain>=10&&gust>=45)return 'Chuva + rajada';if(rain>=10)return 'Chuva';if(gust>=45)return 'Rajada';return e.descricao||'Ameaça climática';}
function climateIsRelevant(e){const level=norm(e.nivel_risco),rain=Number(e.chuva_total_mm||0),gust=Number(e.rajada_kmh||0);return Boolean(e.ameaca_ativa)||Boolean(e.tempestade)||['CRITICO','ALTO','ATENCAO'].includes(level)||rain>=10||gust>=45;}
function climateOfficialMunicipios(){return new Set(defesaEvents.map(e=>norm(e.municipio)).filter(Boolean));}
function climateSortedEvents(){const dc=climateOfficialMunicipios();return weatherEvents.filter(climateIsRelevant).sort((a,b)=>climateSeverityRank(b.nivel_risco)-climateSeverityRank(a.nivel_risco)||Number(Boolean(b.ameaca_ativa))-Number(Boolean(a.ameaca_ativa))||Number(dc.has(norm(b.municipio)))-Number(dc.has(norm(a.municipio)) )||Number(b.rajada_kmh||0)-Number(a.rajada_kmh||0)||Number(b.chuva_total_mm||0)-Number(a.chuva_total_mm||0)||Number(b.sites_ate_4h||0)-Number(a.sites_ate_4h||0)||Number(b.score_risco||0)-Number(a.score_risco||0));}
function climateStripItemHtml(e,dc){const official=dc.has(norm(e.municipio));const rain=Number.isFinite(Number(e.chuva_total_mm))?`${Number(e.chuva_total_mm).toFixed(1)} mm`:null;const gust=Number.isFinite(Number(e.rajada_kmh))?`${Number(e.rajada_kmh).toFixed(1)} km/h`:null;const exposed=Number.isFinite(Number(e.sites_total))?Number(e.sites_total):null;const low=Number.isFinite(Number(e.sites_ate_4h))?Number(e.sites_ate_4h):null;const parts=[`<b>${esc(e.municipio)}</b>`,`<span class="climate-level">${esc(e.nivel_risco||'MONITORAMENTO')}</span>`,`<span>${esc(climateEventType(e))}</span>`];if(rain!==null)parts.push(`<span>🌧️ ${esc(rain)}</span>`);if(gust!==null)parts.push(`<span>💨 ${esc(gust)}</span>`);if(exposed!==null)parts.push(`<span>📡 ${exposed} expostos</span>`);if(low!==null)parts.push(`<span>🔋 ${low} ≤4h</span>`);if(official)parts.push('<span class="climate-official">🚨 Defesa Civil</span>');return `<button type="button" class="climate-strip-item" data-climate-municipio="${esc(e.municipio)}" title="Centralizar ${esc(e.municipio)} no mapa">${parts.join('<i>•</i>')}</button>`;}
function focusClimateMunicipio(name){const e=weatherEvents.find(x=>norm(x.municipio)===norm(name));if(!e)return;const lat=Number(e.latitude),lon=Number(e.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;map.setView([lat,lon],Math.max(map.getZoom(),10),{animate:true});document.getElementById('details').innerHTML=weatherDetailsHtml(e);}
function renderClimateStrip(){const strip=document.getElementById('climateStrip'),track=document.getElementById('climateStripTrack'),status=document.getElementById('climateStripStatus');if(!strip||!track||!status)return;const events=climateSortedEvents(),dc=climateOfficialMunicipios();const max=events.reduce((m,e)=>Math.max(m,climateSeverityRank(e.nivel_risco)),1),sev=max>=4?'critico':max>=3?'alto':max>=2?'atencao':'monitoramento';strip.className=`climate-strip severity-${sev}`;status.textContent=events.length?`${events.length} relevante${events.length===1?'':'s'}${weatherMeta.alertas_oficiais_ativos!=null?` • ${weatherMeta.alertas_oficiais_ativos} alerta(s) oficial(is)`:''}`:'monitoramento normal';if(!events.length){track.className='climate-strip-track climate-strip-static';track.innerHTML='<span class="climate-strip-empty">✅ Sem ameaças climáticas relevantes neste ciclo</span>';return;}const items=events.map(e=>climateStripItemHtml(e,dc)).join('');track.className='climate-strip-track';track.innerHTML=`<div class="climate-strip-run">${items}${items}</div>`;track.querySelectorAll('[data-climate-municipio]').forEach(b=>b.addEventListener('click',()=>focusClimateMunicipio(b.dataset.climateMunicipio)));}

function weatherPopupHtml(e){const ativo=e.ameaca_ativa?'SIM':'NÃO';return `<div class="weather-popup"><b style="color:${weatherColor(e.nivel_risco)}">🌩️ ${esc(e.nivel_risco)}</b><br><b>${esc(e.municipio)}</b><br>Ameaça ativa: <b>${ativo}</b><br>Temperatura: ${esc(e.temperatura_c)} °C<br>Vento atual: ${esc(e.vento_atual_kmh)} km/h<br>Rajada: <b>${esc(e.rajada_kmh)} km/h</b><br>Chuva total: ${esc(e.chuva_total_mm)} mm<br>Prob. chuva: ${esc(e.probabilidade_chuva_pico)}%<br>Tempestade: ${e.tempestade?'SIM':'NÃO'}<br>Sites expostos: ${esc(e.sites_total)}<br>Sites ≤4h: ${esc(e.sites_ate_4h)}</div>`;}
function weatherDetailsHtml(e){const rows=[['Nível',e.nivel_risco],['Município',e.municipio],['Ameaça ativa',e.ameaca_ativa?'SIM':'NÃO'],['Condição',e.descricao],['Temperatura',e.temperatura_c!=null?`${e.temperatura_c} °C`:'—'],['Vento atual',e.vento_atual_kmh!=null?`${e.vento_atual_kmh} km/h`:'—'],['Direção vento',windCompass(e.direcao_vento_graus)],['Vento pico',e.vento_pico_kmh!=null?`${e.vento_pico_kmh} km/h`:'—'],['Rajada',e.rajada_kmh!=null?`${e.rajada_kmh} km/h`:'—'],['Fonte rajada',e.fonte_rajada],['Chuva atual',e.chuva_atual_mm!=null?`${e.chuva_atual_mm} mm`:'—'],['Chuva total',e.chuva_total_mm!=null?`${e.chuva_total_mm} mm`:'—'],['Prob. chuva',e.probabilidade_chuva_pico!=null?`${e.probabilidade_chuva_pico}%`:'—'],['Tempestade',e.tempestade?'SIM':'NÃO'],['Sites expostos',e.sites_total],['Sites ≤4h',e.sites_ate_4h]];return `<div class="panel-title">🌩️ Clima / tempestade</div><h3 class="weather-title" style="color:${weatherColor(e.nivel_risco)}">${esc(e.municipio)} • ${esc(e.nivel_risco)}</h3>${rows.map(r=>`<div class="row"><span>${esc(r[0])}</span><span>${esc(r[1]??'—')}</span></div>`).join('')}<div class="forecast-title">Próximas horas</div>${forecastHtml(e)}`;}
function renderWeather(){weatherLayer.clearLayers();const enabled=document.getElementById('weatherToggle')?.checked!==false;const ativos=weatherEvents.filter(e=>e.ameaca_ativa).length;const count=document.getElementById('weatherCount');if(count){count.textContent=`${ativos} ameaça${ativos===1?'':'s'}`;count.title=`${weatherEvents.length} municípios monitorados`;}if(!enabled)return;weatherEvents.forEach(e=>{const lat=Number(e.latitude),lon=Number(e.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;const color=weatherColor(e.nivel_risco);const active=Boolean(e.ameaca_ativa)||Boolean(e.tempestade);const marker=L.circleMarker([lat,lon],{radius:active?9:6,color:active?'#fff':color,weight:active?2:1,fillColor:color,fillOpacity:active?.9:.42,opacity:active?1:.72});marker.bindPopup(weatherPopupHtml(e));marker.bindTooltip(`🌩️ ${e.municipio||''} • ${e.nivel_risco||''} • rajada ${e.rajada_kmh??'—'} km/h`);marker.on('click',()=>{document.getElementById('details').innerHTML=weatherDetailsHtml(e);});marker.addTo(weatherLayer);});}

function renderForecastSpi(){const sel=document.getElementById('forecastSpiRegion'),sum=document.getElementById('forecastSpiSummary'),wins=document.getElementById('forecastSpiWindows'),src=document.getElementById('forecastSpiSource'),upd=document.getElementById('forecastSpiUpdated');if(!sel||!sum||!wins)return;const regs=forecastSpi.regioes||[];if(!regs.length){sum.textContent='Previsão meteorológica indisponível neste ciclo.';wins.innerHTML='';return}const old=sel.value;if(!sel.options.length||sel.options.length!==regs.length){sel.innerHTML=regs.map(r=>`<option>${esc(r.regiao)}</option>`).join('');if(old&&regs.some(r=>r.regiao===old))sel.value=old}const r=regs.find(x=>x.regiao===sel.value)||regs[0];sel.value=r.regiao;const a=r.atual||{},dir=windCompass(a.wind_direction_10m);sum.innerHTML=`<b>${esc(r.regiao)}</b><div class="forecast-spi-now"><span>🌡️ ${esc(a.temperature_2m??'—')} °C</span><span>💨 ${esc(a.wind_speed_10m??'—')} km/h • ${esc(dir)}</span><span>🌬️ raj. ${esc(a.wind_gusts_10m??'—')} km/h</span><span>${esc(weatherCodeLabel(a.weather_code))}</span></div>`;wins.innerHTML=['6h','12h','24h','48h','72h'].map(k=>{const w=(r.janelas||{})[k]||{};return `<div class="forecast-spi-window ${w.tempestade?'forecast-storm':''}"><b>${k}</b><span>🌧️ ${esc(w.chuva_mm??'—')} mm • ${esc(w.probabilidade_chuva_max??'—')}%</span><span>💨 ${esc(w.vento_max_kmh??'—')} km/h</span><span>🌬️ ${esc(w.rajada_max_kmh??'—')} km/h</span>${w.tempestade?'<strong>⚡ tempestade</strong>':''}</div>`}).join('');if(src)src.textContent=`Fonte: ${forecastSpi.fonte||'—'} • previsão independente das camadas operacionais`;if(upd)upd.textContent=forecastSpi.gerado_em?`Atualizado ${new Date(forecastSpi.gerado_em).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`:'atualizado'}
async function loadForecastSpi(){try{const r=await fetch(`${FORECAST_SPI_DATA}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`Forecast SPI HTTP ${r.status}`);forecastSpi=await r.json();renderForecastSpi()}catch(e){console.error('Falha Previsão SPI',e);const x=document.getElementById('forecastSpiSummary');if(x)x.textContent='Falha ao atualizar previsão meteorológica geral.'}}

async function loadWeather(){try{const r=await fetch(`${WEATHER_DATA}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`Weather HTTP ${r.status}`);const obj=await r.json();weatherMeta={gerado_em:obj.gerado_em,alertas_oficiais_ativos:obj.alertas_oficiais_ativos,fonte_alerta:obj.fonte_alerta};weatherEvents=Array.isArray(obj.eventos)?obj.eventos:[];renderWeather();renderClimateStrip();const c=document.getElementById('weatherCount');if(c&&obj.gerado_em)c.dataset.updated=obj.gerado_em;}catch(err){console.error('Falha Weather Risk',err);const c=document.getElementById('weatherCount');if(c)c.textContent='erro';const s=document.getElementById('climateStripStatus');if(s)s.textContent='erro ao atualizar';}}


function defesaPopupHtml(e){return `<div class="defesa-popup"><b style="color:#ef4444">🚨 DEFESA CIVIL</b><br><b>${esc(e.tipo||e.titulo)}</b><br>Município: <b>${esc(e.municipio)}</b><br>Gravidade: ${esc(e.gravidade)}<br>Urgência: ${esc(e.urgencia)}<br>Certeza: ${esc(e.certeza)}<br>Vigência: ${esc(e.vigencia)}<br><br>${esc(e.resumo)}</div>`;}
function defesaDetailsHtml(e){const rows=[['Tipo',e.tipo||e.titulo],['Município',e.municipio],['Gravidade',e.gravidade],['Urgência',e.urgencia],['Certeza',e.certeza],['Vigência',e.vigencia],['Status',e.status],['Fonte',e.fonte]];return `<div class="panel-title">🚨 Defesa Civil</div><h3 style="color:#ef4444">${esc(e.tipo||e.titulo)}</h3>${rows.map(r=>`<div class="row"><span>${esc(r[0])}</span><span>${esc(r[1]??'—')}</span></div>`).join('')}<p>${esc(e.resumo)}</p>`;}
function renderDefesa(){defesaLayer.clearLayers();const enabled=document.getElementById('defesaToggle')?.checked!==false;const count=document.getElementById('defesaCount');if(count)count.textContent=`${defesaEvents.length} município${defesaEvents.length===1?'':'s'}`;if(!enabled)return;defesaEvents.forEach(e=>{const lat=Number(e.latitude),lon=Number(e.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;const marker=L.circleMarker([lat,lon],{radius:8,color:'#ffffff',weight:2,fillColor:'#ef4444',fillOpacity:.95});marker.bindPopup(defesaPopupHtml(e));marker.bindTooltip(`🚨 ${e.tipo||e.titulo||'Defesa Civil'} • ${e.municipio||''}`);marker.on('click',()=>{document.getElementById('details').innerHTML=defesaDetailsHtml(e);});marker.addTo(defesaLayer);});}

function siteIsCritical(e){return Boolean(e.ate_4h)||norm(e.autonomia).includes('ATE 4H');}
function sitePopupHtml(e){return `<div class="site-popup"><b style="color:${siteIsCritical(e)?'#fb7185':'#7dd3fc'}">📡 ${esc(e.ufsite||e.site)}</b><br><b>${esc(e.municipio)}</b><br>Autonomia: <b>${esc(e.autonomia)}</b><br>Distribuidora: ${esc(e.distribuidora)}<br>DDD: ${esc(e.ddd)}</div>`;}
function siteDetailsHtml(e){const rows=[['Site',e.ufsite||e.site],['Município',e.municipio],['Autonomia',e.autonomia],['Faixa crítica',siteIsCritical(e)?'≤ 4h':'Acima de 4h'],['Distribuidora',e.distribuidora],['DDD',e.ddd],['IBGE',e.ibge]];return `<div class="panel-title">📡 Site</div><h3 style="color:${siteIsCritical(e)?'#fb7185':'#7dd3fc'}">${esc(e.ufsite||e.site)}</h3>${rows.map(r=>`<div class="row"><span>${esc(r[0])}</span><span>${esc(r[1]??'—')}</span></div>`).join('')}`;}
function renderSites(){sitesLayer.clearLayers();const enabled=document.getElementById('sitesToggle')?.checked===true;const count=document.getElementById('sitesCount');const crit=siteEvents.filter(siteIsCritical).length;if(count){count.textContent=`${siteEvents.length.toLocaleString('pt-BR')} • ${crit} ≤4h`;count.title='Sites totais • sites com autonomia até 4h';}if(!enabled)return;const z=map.getZoom();siteEvents.forEach(e=>{const lat=Number(e.latitude),lon=Number(e.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;const c=siteIsCritical(e),radius=z<=7?(c?3.0:2.0):z<=9?(c?4.2:2.8):(c?5.5:3.8);const marker=L.circleMarker([lat,lon],{radius,color:c?'#fecdd3':'#dbeafe',weight:c?1.0:.6,fillColor:c?'#fb7185':'#38bdf8',fillOpacity:c?.92:.58,opacity:.92});marker.bindPopup(sitePopupHtml(e));marker.bindTooltip(`📡 ${e.ufsite||e.site||''} • ${e.municipio||''} • ${e.autonomia||''}`);marker.on('click',()=>{document.getElementById('details').innerHTML=siteDetailsHtml(e);});marker.addTo(sitesLayer);});}
async function loadSites(){try{const r=await fetch(`${SITES_DATA}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`Sites HTTP ${r.status}`);const obj=await r.json();siteEvents=Array.isArray(obj.sites)?obj.sites:[];renderSites();}catch(err){console.error('Falha Sites GEO',err);const c=document.getElementById('sitesCount');if(c)c.textContent='erro';}}

async function loadDefesa(){try{const r=await fetch(`${DEFESA_DATA}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`Defesa Civil HTTP ${r.status}`);const obj=await r.json();defesaEvents=Array.isArray(obj.eventos_geo)?obj.eventos_geo:[];renderDefesa();renderClimateStrip();const c=document.getElementById('defesaCount');if(c)c.title=obj.gerado_em?`Atualizado: ${obj.gerado_em}`:'Defesa Civil';}catch(err){console.error('Falha Defesa Civil',err);const c=document.getElementById('defesaCount');if(c)c.textContent='erro';}}

Promise.all(DATA_FILES.map(u=>fetch(u).then(r=>{if(!r.ok)throw new Error(u);return r.json()}))).then(parts=>{allFeatures=parts.flatMap(p=>p.features||[]);populate();document.getElementById('statusText').textContent=`Backbone DEV carregado • ${allFeatures.length.toLocaleString('pt-BR')} rotas`;if(layer&&allFeatures.length)map.fitBounds(layer.getBounds(),{padding:[20,20]});renderFire();renderWeather();}).catch(err=>{document.getElementById('statusText').textContent='Falha ao carregar Backbone';console.error(err)});
['clusterFilter','confidenceFilter'].forEach(id=>document.getElementById(id).addEventListener('change',render));
document.getElementById('searchBox').addEventListener('input',()=>{clearTimeout(window._t);window._t=setTimeout(render,180)});
document.getElementById('resetBtn').addEventListener('click',()=>{document.getElementById('clusterFilter').value='';document.getElementById('confidenceFilter').value='';document.getElementById('searchBox').value='';render()});
document.getElementById('fireToggle').addEventListener('change',renderFire);
document.getElementById('energyToggle').addEventListener('change',renderEnergy);
map.on('zoomend',renderEnergy);
document.getElementById('weatherToggle').addEventListener('change',renderWeather);
document.getElementById('defesaToggle').addEventListener('change',renderDefesa);
document.getElementById('sitesToggle').addEventListener('change',renderSites);
map.on('zoomend',renderSites);
loadFire();
loadWeather();
loadEnergy();
loadDefesa();
loadSites();
setInterval(loadFire,FIRE_REFRESH_MS);
setInterval(loadWeather,WEATHER_REFRESH_MS);
setInterval(loadEnergy,ENERGY_REFRESH_MS);
setInterval(loadDefesa,DEFESA_REFRESH_MS);
setInterval(loadSites,SITES_REFRESH_MS);


// Analista SPI Vivo DEV — inteligência determinística sobre resultados calculados pelos Cores.
let analystMode='situacao',analystPrev=null,analystHistory=[];
function analystMunicipios(){
  const m=new Map();
  const get=n=>{const k=norm(n);if(!k)return null;if(!m.has(k))m.set(k,{nome:n||k,score:0,sinais:[],sites4h:0});return m.get(k)};
  weatherEvents.forEach(e=>{const x=get(e.municipio);if(!x)return;const ativo=e.ameaca_ativa||e.tempestade,alto=['CRITICO','ALTO'].includes(norm(e.nivel_risco));if(ativo){x.score+=4;x.sinais.push('clima')};if(alto){x.score+=5;x.sinais.push(norm(e.nivel_risco))};const r=Number(e.rajada_kmh||0);if(r>=60){x.score+=4;x.sinais.push(`rajada ${r} km/h`)}else if(r>=45){x.score+=2;x.sinais.push(`rajada ${r} km/h`)};const ch=Number(e.chuva_total_mm||0);if(ch>=20){x.score+=4;x.sinais.push(`chuva ${ch} mm`)}else if(ch>=10){x.score+=2;x.sinais.push(`chuva ${ch} mm`)}});
  defesaEvents.forEach(e=>{const x=get(e.municipio);if(x){x.score+=4;x.sinais.push('Defesa Civil')}});
  energyEvents.forEach(e=>{const x=get(e.municipio);if(x){x.score+=3;x.sinais.push('energia')}});
  fireEvents.forEach(e=>{const x=get(e.municipio);if(x){x.score+=norm(e.classificacao)==='URGENTE'?7:3;x.sinais.push(`Fire ${e.classificacao||''}`.trim())}});
  siteEvents.filter(siteIsCritical).forEach(e=>{const x=get(e.municipio);if(x){x.sites4h+=1;x.score+=1}});
  return [...m.values()].sort((a,b)=>b.score-a.score||b.sites4h-a.sites4h||a.nome.localeCompare(b.nome,'pt-BR'));
}
function analystSnapshot(){const threats=weatherEvents.filter(e=>e.ameaca_ativa||e.tempestade),critical=weatherEvents.filter(e=>['CRITICO','ALTO'].includes(norm(e.nivel_risco))),vulnerable=weatherEvents.filter(e=>Number(e.sites_ate_4h||0)>0),maxGust=[...weatherEvents].sort((a,b)=>Number(b.rajada_kmh||0)-Number(a.rajada_kmh||0))[0],maxRain=[...weatherEvents].sort((a,b)=>Number(b.chuva_total_mm||0)-Number(a.chuva_total_mm||0))[0],fireUrg=fireEvents.filter(e=>norm(e.classificacao)==='URGENTE'),dc=new Set(defesaEvents.map(e=>norm(e.municipio)).filter(Boolean)),convergence=weatherEvents.filter(w=>dc.has(norm(w.municipio))&&(w.ameaca_ativa||w.tempestade)),critSites=siteEvents.filter(siteIsCritical),affected=new Set([...threats.map(e=>norm(e.municipio)),...defesaEvents.map(e=>norm(e.municipio)),...energyEvents.map(e=>norm(e.municipio)),...fireEvents.map(e=>norm(e.municipio))].filter(Boolean)),exposedCritSites=critSites.filter(e=>affected.has(norm(e.municipio))),municipios=analystMunicipios();let score=threats.length*4+critical.length*6+fireUrg.length*7+fireEvents.length*2+convergence.length*5+Math.min(energyEvents.length,20)+Math.min(exposedCritSites.length,20),readiness='PREPARADA';if(critical.length||fireUrg.length||threats.length>=5)readiness='CRÍTICA';else if(threats.length||fireEvents.length||defesaEvents.length||energyEvents.length)readiness='ATENÇÃO';return{threats,critical,vulnerable,maxGust,maxRain,fireUrg,convergence,critSites,exposedCritSites,municipios,readiness,score}}
function analystTrend(s){if(!analystPrev)return{label:'● AO VIVO',level:'stable',change:'Linha de base operacional estabelecida. O painel agora reage às atualizações dos Cores.'};const d=s.score-analystPrev.score;if(d>=5)return{label:'↑ RISCO AUMENTANDO',level:'up',change:`⚠️ Mudança detectada: pressão operacional aumentou (+${d} pontos).`};if(d<=-5)return{label:'↓ RISCO REDUZINDO',level:'down',change:`✅ Mudança detectada: pressão operacional reduziu (${d} pontos).`};return{label:'→ SEM MUDANÇA MATERIAL',level:'stable',change:'🔎 As fontes atualizaram, mas não houve alteração material do quadro operacional.'}}
function analystTop(s,n=3){return s.municipios.filter(x=>x.score>0).slice(0,n)}
function analystText(mode='situacao',question=''){const s=analystSnapshot(),gust=s.maxGust?`${s.maxGust.municipio}: ${s.maxGust.rajada_kmh} km/h`:'sem dado',rain=s.maxRain?`${s.maxRain.municipio}: ${s.maxRain.chuva_total_mm} mm`:'sem dado',top=analystTop(s),lines=[];const topTxt=top.length?top.map((x,i)=>`${i+1}. <b>${esc(x.nome)}</b> — ${[...new Set(x.sinais)].slice(0,3).map(esc).join(' + ')}${x.sites4h?` • ${x.sites4h} site(s) ≤4h`:''}`).join('<br>'):'Nenhum município com sinal operacional relevante neste ciclo.';
if(mode==='preparacao'){lines.push(`<b>🎯 Preparação da Regional — ${s.readiness}</b>`);lines.push(`<b>Onde agir primeiro</b><br>${topTxt}`);lines.push(`Hoje o painel cruza ${s.threats.length} ameaça(s) climática(s), ${s.convergence.length} convergência(s) clima + Defesa Civil e ${s.exposedCritSites.length} site(s) ≤4h em municípios presentes nas camadas de risco/impacto.`);if(top.length)lines.push(`📌 <b>Ação recomendada agora:</b> validar GMGs, autonomia real, equipes, acesso e escalonamento começando por ${esc(top[0].nome)}${top[1]?` e ${esc(top[1].nome)}`:''}.`);else lines.push('📌 <b>Ação recomendada agora:</b> manter prontidão e acompanhar mudanças dos Cores.');if(s.convergence.length)lines.push(`🚨 Há convergência clima + Defesa Civil em ${s.convergence.length} município(s), elevando a prioridade de acompanhamento.`)}else if(mode==='projecao'){lines.push('<b>🛰️ Projeção operacional</b>');lines.push(`Maior rajada disponível: ${esc(gust)}. Maior chuva total disponível: ${esc(rain)}.`);if(top.length)lines.push(`<b>Corredor de atenção atual</b><br>${topTxt}`);lines.push('Origem, trajetória, chegada, pico e saída só serão apresentados quando vierem de cálculo/fonte meteorológica estruturada. O Analista não inventa deslocamento.')}else{lines.push(`<b>📡 SPI agora — ${s.readiness}</b>`);lines.push(`Clima ${s.threats.length} ameaça(s) • Energia ${energyEvents.length} região(ões) • Fire ${fireEvents.length} • Defesa Civil ${defesaEvents.length} município(s) • ${s.exposedCritSites.length} site(s) ≤4h expostos.`);lines.push(`<b>Prioridades neste instante</b><br>${topTxt}`);lines.push(`Picos disponíveis: rajada ${esc(gust)}; chuva ${esc(rain)}.`);if(s.critical.length)lines.push(`⚠️ ${s.critical.length} município(s) estão em nível ALTO/CRÍTICO no Weather Risk.`)}
if(question){const q=norm(question);if(q.includes('ONDE')||q.includes('ATENCAO')||q.includes('PRIOR'))lines.push(`<b>Resposta:</b><br>${topTxt}`);else if(q.includes('QUEIM')||q.includes('FOGO'))lines.push(`<b>Resposta:</b> ${fireEvents.length} evento(s) Fire ativo(s).`);else if(q.includes('ENERG'))lines.push(`<b>Resposta:</b> ${energyEvents.length} região(ões) na camada Energia.`);else if(q.includes('DEFESA'))lines.push(`<b>Resposta:</b> ${defesaEvents.length} município(s) na Defesa Civil.`);else if(q.includes('SITE')||q.includes('AUTON'))lines.push(`<b>Resposta:</b> ${s.critSites.length} sites ≤4h na base; ${s.exposedCritSites.length} em municípios presentes nas camadas operacionais atuais.`);else if(q.includes('CHUVA'))lines.push(`<b>Resposta:</b> maior chuva disponível: ${esc(rain)}.`);else if(q.includes('VENTO')||q.includes('RAJADA'))lines.push(`<b>Resposta:</b> maior rajada disponível: ${esc(gust)}.`);else lines.push(`<b>Resposta operacional:</b> quadro ${s.readiness}. Prioridade atual: ${top.length?esc(top[0].nome):'sem município prioritário'}.`)}return lines.join('<br><br>')}
function setAnalystActive(mode){document.querySelectorAll('[data-analysis]').forEach(b=>{const a=b.dataset.analysis===mode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a?'true':'false')})}
function refreshAnalyst(){const p=document.getElementById('analystPanel');if(!p)return;const s=analystSnapshot(),t=analystTrend(s),badge=document.getElementById('readinessBadge');badge.textContent=s.readiness;badge.dataset.level=norm(s.readiness);document.getElementById('analystSummary').innerHTML=analystText(analystMode);document.getElementById('analystUpdated').textContent=`Fire ${fireEvents.length} • Clima ${weatherEvents.length} • Energia ${energyEvents.length} • Defesa ${defesaEvents.length} • Sites ${siteEvents.length}`;const tr=document.getElementById('analystTrend');tr.textContent=t.label;tr.dataset.level=t.level;document.getElementById('analystChange').textContent=t.change;document.getElementById('analystClock').textContent=`Analisado ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;const top=analystTop(s,2);document.getElementById('analystWatch').textContent=`${s.threats.length} ameaça(s) clima • ${s.convergence.length} convergência(s) Defesa • ${s.exposedCritSites.length} sites ≤4h expostos${top.length?` • foco: ${top.map(x=>x.nome).join(' / ')}`:''}`;if(!analystPrev||t.level!=='stable'){analystHistory.unshift(`${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} — ${t.label}`);analystHistory=analystHistory.slice(0,4)}document.getElementById('analystTimeline').innerHTML='<b>🕒 Linha do tempo desta sessão</b>'+analystHistory.map(x=>`<div>${esc(x)}</div>`).join('');analystPrev=s;setAnalystActive(analystMode)}
function analystRun(mode){analystMode=mode||'situacao';refreshAnalyst();const x=document.getElementById('analystSummary');x.classList.remove('analyst-flash');void x.offsetWidth;x.classList.add('analyst-flash')}
function analystAsk(){const q=document.getElementById('analystQuestion').value.trim(),a=document.getElementById('analystAnswer');a.innerHTML=q?analystText('situacao',q):'<b>Digite uma pergunta para o Analista SPI.</b>';a.classList.remove('analyst-flash');void a.offsetWidth;a.classList.add('analyst-flash')}
document.querySelectorAll('[data-analysis]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();analystRun(b.dataset.analysis)}));document.getElementById('analystAsk')?.addEventListener('click',e=>{e.preventDefault();analystAsk()});document.getElementById('analystQuestion')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();analystAsk()}});setAnalystActive(analystMode);setInterval(refreshAnalyst,10000);setTimeout(refreshAnalyst,1200);

document.getElementById('forecastSpiRegion')?.addEventListener('change',renderForecastSpi);
loadForecastSpi();
setInterval(loadForecastSpi,FORECAST_SPI_REFRESH_MS);
