const map=L.map('map',{preferCanvas:true,zoomControl:true}).setView([-22.45,-48.4],7);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);
const DATA_FILES=['data/backbone-1.geojson','data/backbone-2.geojson','data/backbone-3.geojson','data/backbone-4.geojson'];
let allFeatures=[],layer=null;
const colorFor=c=>({ALTA:'#7c3aed',MEDIA:'#f59e0b',BAIXA:'#ef4444',SEM_REFERENCIA:'#64748b'})[c]||'#38bdf8';
const norm=v=>(v??'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
function popupHtml(p){return `<b>${p.trecho||'Backbone'}</b><br>${p.ponta_a||'—'} — ${p.municipio_a||'—'}<br>${p.ponta_b||'—'} — ${p.municipio_b||'—'}<br>Cabo: <b>${p.cabo||'—'}</b><br>Confiança: ${p.confianca||'—'}`;}
function detailsHtml(p){const rows=[['Trecho',p.trecho],['Cabo',p.cabo],['Capacidade',p.capacidade],['Cluster',p.cluster],['Ponta A',`${p.ponta_a||'—'} — ${p.municipio_a||'—'}`],['Ponta B',`${p.ponta_b||'—'} — ${p.municipio_b||'—'}`],['Extensão',p.extensao_km?`${Number(p.extensao_km).toFixed(2)} km`:'—'],['Confiança',p.confianca],['Fonte',p.fonte]];return `<div class="panel-title">Trecho selecionado</div><h3>${p.trecho||'Backbone'}</h3>${rows.map(r=>`<div class="row"><span>${r[0]}</span><span>${r[1]??'—'}</span></div>`).join('')}`;}
function render(){const cl=document.getElementById('clusterFilter').value,cf=document.getElementById('confidenceFilter').value,q=norm(document.getElementById('searchBox').value);const feats=allFeatures.filter(f=>{const p=f.properties||{};if(cl&&p.cluster!==cl)return false;if(cf&&p.confianca!==cf)return false;if(q&&!norm([p.trecho,p.cabo,p.cluster,p.ponta_a,p.ponta_b,p.municipio_a,p.municipio_b].join(' ')).includes(q))return false;return true;});if(layer)layer.remove();layer=L.geoJSON({type:'FeatureCollection',features:feats},{style:f=>({color:colorFor(f.properties.confianca),weight:3,opacity:.78}),onEachFeature:(f,l)=>{l.bindPopup(popupHtml(f.properties));l.on('click',()=>document.getElementById('details').innerHTML=detailsHtml(f.properties));l.on('mouseover',()=>l.setStyle({weight:6,opacity:1}));l.on('mouseout',()=>layer.resetStyle(l));}}).addTo(map);document.getElementById('rotas').textContent=feats.length.toLocaleString('pt-BR');if(feats.length&&q)try{map.fitBounds(layer.getBounds(),{padding:[20,20],maxZoom:12})}catch(e){}}
function populate(){const ps=allFeatures.map(f=>f.properties||{});const uniq=k=>[...new Set(ps.map(p=>p[k]).filter(Boolean))];document.getElementById('clusters').textContent=uniq('cluster').length;document.getElementById('cabos').textContent=uniq('cabo').length;document.getElementById('municipios').textContent=new Set(ps.flatMap(p=>[p.municipio_a,p.municipio_b]).filter(Boolean)).size;const s=document.getElementById('clusterFilter');uniq('cluster').sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o)});render();}
Promise.all(DATA_FILES.map(u=>fetch(u).then(r=>{if(!r.ok)throw new Error(u);return r.json()}))).then(parts=>{allFeatures=parts.flatMap(p=>p.features||[]);populate();document.getElementById('statusText').textContent=`Backbone DEV carregado • ${allFeatures.length.toLocaleString('pt-BR')} rotas`;if(layer&&allFeatures.length)map.fitBounds(layer.getBounds(),{padding:[20,20]});}).catch(err=>{document.getElementById('statusText').textContent='Falha ao carregar Backbone';console.error(err)});
['clusterFilter','confidenceFilter'].forEach(id=>document.getElementById(id).addEventListener('change',render));
document.getElementById('searchBox').addEventListener('input',()=>{clearTimeout(window._t);window._t=setTimeout(render,180)});
document.getElementById('resetBtn').addEventListener('click',()=>{document.getElementById('clusterFilter').value='';document.getElementById('confidenceFilter').value='';document.getElementById('searchBox').value='';render()});